/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarImg: typeof import('./src/components/FileUpload/avatar-img.vue')['default']
    BarStackEcharts: typeof import('./src/components/PageEcharts/src/bar-stack-echarts.vue')['default']
    BaseEcharts: typeof import('./src/components/PageEcharts/src/base-echarts.vue')['default']
    Breadcrumb: typeof import('./src/components/MainHeader/breadcrumb.vue')['default']
    DoubleImg: typeof import('./src/components/FileUpload/double-img.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HeadUserinfo: typeof import('./src/components/MainHeader/head-userinfo.vue')['default']
    KlineEcharts: typeof import('./src/components/PageEcharts/src/kline-echarts.vue')['default']
    LineEcharts: typeof import('./src/components/PageEcharts/src/line-echarts.vue')['default']
    LogoCpn: typeof import('./src/components/MainMenu/logo-cpn.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader/index.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu/index.vue')['default']
    MapEcharts: typeof import('./src/components/PageEcharts/src/map-echarts.vue')['default']
    MapEchartsTest: typeof import('./src/components/PageEcharts/src/map-echarts-test.vue')['default']
    MenusCpn: typeof import('./src/components/MainMenu/menus-cpn.vue')['default']
    PieEcharts: typeof import('./src/components/PageEcharts/src/pie-echarts.vue')['default']
    RotateCube: typeof import('./src/components/AnimateCss3/rotate-cube.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideButtons: typeof import('./src/components/SideButtons/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
