/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarImg: typeof import('./src/components/FileUpload/avatar-img.vue')['default']
    BarStackEcharts: typeof import('./src/components/PageEcharts/src/bar-stack-echarts.vue')['default']
    BaseEcharts: typeof import('./src/components/PageEcharts/src/base-echarts.vue')['default']
    Breadcrumb: typeof import('./src/components/MainHeader/breadcrumb.vue')['default']
    DoubleImg: typeof import('./src/components/FileUpload/double-img.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    HeadUserinfo: typeof import('./src/components/MainHeader/head-userinfo.vue')['default']
    KlineEcharts: typeof import('./src/components/PageEcharts/src/kline-echarts.vue')['default']
    LineEcharts: typeof import('./src/components/PageEcharts/src/line-echarts.vue')['default']
    LogoCpn: typeof import('./src/components/MainMenu/logo-cpn.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader/index.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu/index.vue')['default']
    MapEcharts: typeof import('./src/components/PageEcharts/src/map-echarts.vue')['default']
    MenusCpn: typeof import('./src/components/MainMenu/menus-cpn.vue')['default']
    PieEcharts: typeof import('./src/components/PageEcharts/src/pie-echarts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideButtons: typeof import('./src/components/SideButtons/index.vue')['default']
  }
}
